version: '3'

######### Services ###################################

services:
  # Server container
  nginx:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
      - ./docker/nginx/logs:/var/log/nginx
    ports:
      - 8080:80
    links:
      - php

  # PHP FastCGI Process Manager container
  php:
    build:
      context: docker/php
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
  mysql:
    build:
      context: docker/mysql
      dockerfile: Dockerfile
    volumes:
      - db:/var/lib/mysql
      - ./docker/mysql/logs:/var/log/mysql
    ports:
      - 3131:3306
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: secret
    command: mysqld --sql_mode=""

volumes:
  db:
    external: true
